In [11]:
import sys
import os
import importlib.util
import sqlite3
import pandas as pd
import sys
import pycountry


parent_dir = os.path.abspath('../')
scraper_path = os.path.join(parent_dir)
sys.path.append(scraper_path)

In [2]:
from scrappers.article_extractor import ArticleExtractor

In [3]:
from scrappers.rss_scraper import RssScraper

   
scraper = RssScraper()

# frequency: 1=hourly, 2=every 4 hours, 3=every 6 hours, 4=daily
scraper.add_source("CNN", "http://rss.cnn.com/rss/cnn_topstories.rss", 1)
scraper.add_source("BBC", "http://feeds.bbci.co.uk/news/rss.xml", 1)
scraper.add_source("NYT", "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml", 2)

2025-04-12 10:22:04,497 - rss_scraper - WARNING - Source with URL http://rss.cnn.com/rss/cnn_topstories.rss already exists
2025-04-12 10:22:04,499 - rss_scraper - WARNING - Source with URL http://feeds.bbci.co.uk/news/rss.xml already exists
2025-04-12 10:22:04,500 - rss_scraper - WARNING - Source with URL https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml already exists

In [4]:
data = scraper.scrape_feeds(force=True)

2025-04-12 10:22:06,424 - rss_scraper - INFO - Found 4 sources
2025-04-12 10:22:06,425 - rss_scraper - INFO - Scraping feed: CNN (http://rss.cnn.com/rss/cnn_topstories.rss)
2025-04-12 10:22:07,265 - rss_scraper - INFO - Found 16 articles from CNN
2025-04-12 10:22:09,276 - rss_scraper - INFO - Scraping feed: BBC (http://feeds.bbci.co.uk/news/rss.xml)
2025-04-12 10:22:09,483 - rss_scraper - INFO - Found 35 articles from BBC
2025-04-12 10:22:11,495 - rss_scraper - INFO - Scraping feed: NYT (https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml)
2025-04-12 10:22:12,607 - rss_scraper - INFO - Found 23 articles from NYT
2025-04-12 10:22:14,619 - rss_scraper - INFO - Scraping feed: New Scientist (https://www.newscientist.com/feed/home/?cmpid=RSS%7CNSNS-Home)
2025-04-12 10:22:21,002 - rss_scraper - INFO - Found 51 articles from New Scientist
2025-04-12 10:22:23,018 - rss_scraper - INFO - Completed scraping, found 125 new articles
2025-04-12 10:22:23,040 - rss_scraper - INFO - Found 105 articles pending content extraction
2025-04-12 10:22:23,043 - rss_scraper - INFO - Starting content extraction with 5 workers, batch size: 50
2025-04-12 10:22:23,047 - article_extractor - INFO - Found 50 articles to process
2025-04-12 10:22:23,062 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/czx40yvzqk0o
2025-04-12 10:22:23,072 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/crm3kxxx8x9o
2025-04-12 10:22:23,076 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/c5yg690e9eno
2025-04-12 10:22:23,084 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/c4g86jy6jggo
2025-04-12 10:22:23,086 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/cwy0ngd11yzo
2025-04-12 10:22:24,814 - article_extractor - INFO - Extracting content from: https://www.bbc.com/weather/articles/c99p142g143o
2025-04-12 10:22:24,837 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/czx40yvzqk0o in database
2025-04-12 10:22:24,840 - article_extractor - INFO - Processed article 1/50: https://www.bbc.com/news/articles/czx40yvzqk0o
2025-04-12 10:22:26,604 - readability.readability - INFO - ruthless removal did not work.
2025-04-12 10:22:26,691 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/c2kvqnx0dnno
2025-04-12 10:22:32,120 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/c209ndewxy3o
2025-04-12 10:22:32,131 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/c5y66y40kgpo
2025-04-12 10:22:32,156 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/c89gge1820lo
2025-04-12 10:22:32,245 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/crm3kxxx8x9o in database
2025-04-12 10:22:32,253 - article_extractor - INFO - Processed article 2/50: https://www.bbc.com/news/articles/crm3kxxx8x9o
2025-04-12 10:22:32,256 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/cq5wlevy647o
2025-04-12 10:22:32,301 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/c5yg690e9eno in database
2025-04-12 10:22:32,303 - article_extractor - INFO - Processed article 3/50: https://www.bbc.com/news/articles/c5yg690e9eno
2025-04-12 10:22:32,358 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/c4g86jy6jggo in database
2025-04-12 10:22:32,359 - article_extractor - INFO - Processed article 4/50: https://www.bbc.com/news/articles/c4g86jy6jggo
2025-04-12 10:22:32,402 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/c0r51d2r8peo
2025-04-12 10:22:32,414 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/cwy0ngd11yzo in database
2025-04-12 10:22:32,416 - article_extractor - INFO - Processed article 5/50: https://www.bbc.com/news/articles/cwy0ngd11yzo
2025-04-12 10:22:32,452 - article_extractor - INFO - Updated article https://www.bbc.com/weather/articles/c99p142g143o in database
2025-04-12 10:22:32,454 - article_extractor - INFO - Processed article 6/50: https://www.bbc.com/weather/articles/c99p142g143o
2025-04-12 10:22:32,468 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/c2kvqnx0dnno in database
2025-04-12 10:22:32,469 - article_extractor - INFO - Processed article 7/50: https://www.bbc.com/news/articles/c2kvqnx0dnno
2025-04-12 10:22:36,609 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/c5yl8jnl4gno
2025-04-12 10:22:36,896 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/c9w8g7jlkpwo
2025-04-12 10:22:36,982 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/c62gnzzeg34o
2025-04-12 10:22:37,038 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/cgeng08qe7zo
2025-04-12 10:22:37,046 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/c209ndewxy3o in database
2025-04-12 10:22:37,073 - article_extractor - INFO - Processed article 8/50: https://www.bbc.com/news/articles/c209ndewxy3o
2025-04-12 10:22:37,085 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/c9veeypj93eo
2025-04-12 10:22:37,091 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/c5y66y40kgpo in database
2025-04-12 10:22:37,092 - article_extractor - INFO - Processed article 9/50: https://www.bbc.com/news/articles/c5y66y40kgpo
2025-04-12 10:22:37,098 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/c89gge1820lo in database
2025-04-12 10:22:37,099 - article_extractor - INFO - Processed article 10/50: https://www.bbc.com/news/articles/c89gge1820lo
2025-04-12 10:22:37,109 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/cq5wlevy647o in database
2025-04-12 10:22:37,110 - article_extractor - INFO - Processed article 11/50: https://www.bbc.com/news/articles/cq5wlevy647o
2025-04-12 10:22:37,122 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/c0r51d2r8peo in database
2025-04-12 10:22:37,123 - article_extractor - INFO - Processed article 12/50: https://www.bbc.com/news/articles/c0r51d2r8peo
2025-04-12 10:22:37,573 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/cwy7vr456ppo
2025-04-12 10:22:37,581 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/c5yl8jnl4gno in database
2025-04-12 10:22:37,582 - article_extractor - INFO - Processed article 13/50: https://www.bbc.com/news/articles/c5yl8jnl4gno
2025-04-12 10:22:40,700 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/cly80970p2ko
2025-04-12 10:22:40,922 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/cp8kmrg1p8go
2025-04-12 10:22:40,980 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/c705nxgqvv8o
2025-04-12 10:22:41,042 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/c20xxv22wl9o
2025-04-12 10:22:41,105 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/cjew7y4j724o
2025-04-12 10:22:41,121 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/c9w8g7jlkpwo in database
2025-04-12 10:22:41,121 - article_extractor - INFO - Processed article 14/50: https://www.bbc.com/news/articles/c9w8g7jlkpwo
2025-04-12 10:22:41,125 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/c62gnzzeg34o in database
2025-04-12 10:22:41,125 - article_extractor - INFO - Processed article 15/50: https://www.bbc.com/news/articles/c62gnzzeg34o
2025-04-12 10:22:41,129 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/cgeng08qe7zo in database
2025-04-12 10:22:41,129 - article_extractor - INFO - Processed article 16/50: https://www.bbc.com/news/articles/cgeng08qe7zo
2025-04-12 10:22:41,133 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/c9veeypj93eo in database
2025-04-12 10:22:41,133 - article_extractor - INFO - Processed article 17/50: https://www.bbc.com/news/articles/c9veeypj93eo
2025-04-12 10:22:41,137 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/cwy7vr456ppo in database
2025-04-12 10:22:41,137 - article_extractor - INFO - Processed article 18/50: https://www.bbc.com/news/articles/cwy7vr456ppo
2025-04-12 10:22:44,373 - article_extractor - INFO - Extracting content from: https://www.bbc.com/sport/mixed-martial-arts/articles/cwynngn09kko
2025-04-12 10:22:44,443 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/cwy6gjwd0g6o
2025-04-12 10:22:44,498 - article_extractor - INFO - Extracting content from: https://www.bbc.com/news/articles/clyqj2739zdo
2025-04-12 10:22:44,529 - article_extractor - INFO - Extracting content from: https://www.bbc.co.uk/sounds/play/p0l3nm64
2025-04-12 10:22:44,536 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/cly80970p2ko in database
2025-04-12 10:22:44,656 - article_extractor - INFO - Extracting content from: https://www.bbc.co.uk/sounds/play/m0029rs1
2025-04-12 10:22:44,656 - article_extractor - INFO - Processed article 19/50: https://www.bbc.com/news/articles/cly80970p2ko
2025-04-12 10:22:44,660 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/cp8kmrg1p8go in database
2025-04-12 10:22:44,661 - article_extractor - INFO - Processed article 20/50: https://www.bbc.com/news/articles/cp8kmrg1p8go
2025-04-12 10:22:44,665 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/c705nxgqvv8o in database
2025-04-12 10:22:44,666 - article_extractor - INFO - Processed article 21/50: https://www.bbc.com/news/articles/c705nxgqvv8o
2025-04-12 10:22:44,671 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/c20xxv22wl9o in database
2025-04-12 10:22:44,672 - article_extractor - INFO - Processed article 22/50: https://www.bbc.com/news/articles/c20xxv22wl9o
2025-04-12 10:22:44,675 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/cjew7y4j724o in database
2025-04-12 10:22:44,677 - article_extractor - INFO - Processed article 23/50: https://www.bbc.com/news/articles/cjew7y4j724o
2025-04-12 10:22:44,821 - article_extractor - WARNING - Paywall detected for https://www.bbc.co.uk/sounds/play/p0l3nm64
2025-04-12 10:22:44,911 - article_extractor - INFO - Extracting content from: https://www.bbc.com/sport/golf/articles/clyqgd5z495o
2025-04-12 10:22:47,299 - readability.readability - INFO - ruthless removal did not work.
2025-04-12 10:22:47,334 - readability.readability - INFO - ruthless removal did not work.
2025-04-12 10:22:47,412 - article_extractor - INFO - Extracting content from: https://www.bbc.com/sport/rugby-union/articles/cqx4e2x4g3ro
2025-04-12 10:22:47,469 - article_extractor - INFO - Extracting content from: https://www.bbc.com/sport/football/articles/c20xngdprpyo
2025-04-12 10:22:47,549 - article_extractor - INFO - Extracting content from: https://www.bbc.com/sport/formula1/articles/c98g9dpe6dro
2025-04-12 10:22:47,554 - article_extractor - INFO - Updated article https://www.bbc.com/sport/mixed-martial-arts/articles/cwynngn09kko in database
2025-04-12 10:22:47,560 - article_extractor - INFO - Processed article 24/50: https://www.bbc.com/sport/mixed-martial-arts/articles/cwynngn09kko
2025-04-12 10:22:47,570 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/cwy6gjwd0g6o in database
2025-04-12 10:22:47,626 - article_extractor - INFO - Extracting content from: https://www.bbc.com/sport/cycling/articles/cp34q8459xno
2025-04-12 10:22:47,627 - article_extractor - INFO - Processed article 25/50: https://www.bbc.com/news/articles/cwy6gjwd0g6o
2025-04-12 10:22:47,632 - article_extractor - INFO - Updated article https://www.bbc.com/news/articles/clyqj2739zdo in database
2025-04-12 10:22:47,633 - article_extractor - INFO - Processed article 26/50: https://www.bbc.com/news/articles/clyqj2739zdo
2025-04-12 10:22:47,637 - article_extractor - INFO - Updated article https://www.bbc.co.uk/sounds/play/p0l3nm64 in database
2025-04-12 10:22:47,638 - article_extractor - INFO - Processed article 27/50: https://www.bbc.co.uk/sounds/play/p0l3nm64
2025-04-12 10:22:48,090 - article_extractor - WARNING - Paywall detected for https://www.bbc.co.uk/sounds/play/m0029rs1
2025-04-12 10:22:48,323 - article_extractor - INFO - Extracting content from: https://www.bbc.com/sport/football/articles/c74zkrx7zzgo
2025-04-12 10:22:48,329 - article_extractor - INFO - Updated article https://www.bbc.co.uk/sounds/play/m0029rs1 in database
2025-04-12 10:22:48,329 - article_extractor - INFO - Processed article 28/50: https://www.bbc.co.uk/sounds/play/m0029rs1
2025-04-12 10:22:48,333 - article_extractor - INFO - Updated article https://www.bbc.com/sport/golf/articles/clyqgd5z495o in database
2025-04-12 10:22:48,335 - article_extractor - INFO - Processed article 29/50: https://www.bbc.com/sport/golf/articles/clyqgd5z495o
2025-04-12 10:22:50,733 - readability.readability - INFO - ruthless removal did not work.
2025-04-12 10:22:50,800 - readability.readability - INFO - ruthless removal did not work.
2025-04-12 10:22:50,811 - readability.readability - INFO - ruthless removal did not work.
2025-04-12 10:22:50,823 - readability.readability - INFO - ruthless removal did not work.
2025-04-12 10:22:50,844 - readability.readability - INFO - ruthless removal did not work.
2025-04-12 10:22:50,933 - article_extractor - INFO - Extracting content from: https://www.bbc.com/sport/golf/videos/c4g978d0ge5o
2025-04-12 10:22:50,998 - article_extractor - INFO - Extracting content from: https://www.nytimes.com/2025/04/11/business/us-china-tariffs-trump-xi.html
2025-04-12 10:22:51,052 - article_extractor - INFO - Extracting content from: https://www.nytimes.com/2025/04/11/business/economy/treasury-bonds-tariffs.html
2025-04-12 10:22:51,107 - article_extractor - INFO - Extracting content from: https://www.nytimes.com/2025/04/12/world/asia/taiwan-exporters-tariffs.html
2025-04-12 10:22:51,119 - article_extractor - INFO - Updated article https://www.bbc.com/sport/rugby-union/articles/cqx4e2x4g3ro in database
2025-04-12 10:22:51,123 - article_extractor - INFO - Processed article 30/50: https://www.bbc.com/sport/rugby-union/articles/cqx4e2x4g3ro
2025-04-12 10:22:51,132 - article_extractor - INFO - Updated article https://www.bbc.com/sport/football/articles/c20xngdprpyo in database
2025-04-12 10:22:51,184 - article_extractor - INFO - Extracting content from: https://www.nytimes.com/2025/04/11/us/politics/us-maryland-man-deportation-delay.html
2025-04-12 10:22:51,186 - article_extractor - INFO - Processed article 31/50: https://www.bbc.com/sport/football/articles/c20xngdprpyo
2025-04-12 10:22:51,191 - article_extractor - INFO - Updated article https://www.bbc.com/sport/formula1/articles/c98g9dpe6dro in database
2025-04-12 10:22:51,192 - article_extractor - INFO - Processed article 32/50: https://www.bbc.com/sport/formula1/articles/c98g9dpe6dro
2025-04-12 10:22:51,196 - article_extractor - INFO - Updated article https://www.bbc.com/sport/cycling/articles/cp34q8459xno in database
2025-04-12 10:22:51,197 - article_extractor - INFO - Processed article 33/50: https://www.bbc.com/sport/cycling/articles/cp34q8459xno
2025-04-12 10:22:51,202 - article_extractor - INFO - Updated article https://www.bbc.com/sport/football/articles/c74zkrx7zzgo in database
2025-04-12 10:22:51,203 - article_extractor - INFO - Processed article 34/50: https://www.bbc.com/sport/football/articles/c74zkrx7zzgo
2025-04-12 10:22:51,432 - article_extractor - INFO - Extracting content from: https://www.nytimes.com/2025/04/11/nyregion/khalil-jena-deportation-ruling.html
2025-04-12 10:22:52,356 - article_extractor - WARNING - Paywall detected for https://www.bbc.com/sport/golf/videos/c4g978d0ge5o
2025-04-12 10:22:52,483 - readability.readability - INFO - ruthless removal did not work.
2025-04-12 10:22:52,538 - article_extractor - INFO - Extracting content from: https://www.nytimes.com/2025/04/11/us/politics/immigration-enforcement-places-of-worship.html
2025-04-12 10:22:52,542 - article_extractor - INFO - Updated article https://www.bbc.com/sport/golf/videos/c4g978d0ge5o in database
2025-04-12 10:22:52,543 - article_extractor - INFO - Processed article 35/50: https://www.bbc.com/sport/golf/videos/c4g978d0ge5o
2025-04-12 10:22:52,546 - article_extractor - INFO - Updated article https://www.nytimes.com/2025/04/11/business/us-china-tariffs-trump-xi.html in database
2025-04-12 10:22:52,547 - article_extractor - INFO - Processed article 36/50: https://www.nytimes.com/2025/04/11/business/us-china-tariffs-trump-xi.html
2025-04-12 10:22:54,572 - article_extractor - INFO - Extracting content from: https://www.nytimes.com/2025/04/11/us/politics/trump-military-border.html
2025-04-12 10:22:54,591 - article_extractor - INFO - Extracting content from: https://www.nytimes.com/2025/04/11/business/trump-law-firms-kirkland-ellis-latham-watkins.html
2025-04-12 10:22:54,721 - article_extractor - INFO - Extracting content from: https://www.nytimes.com/2025/04/11/us/politics/naval-academy-banned-books.html
2025-04-12 10:22:54,865 - article_extractor - INFO - Extracting content from: https://www.nytimes.com/2025/04/11/climate/noaa-research-budget-cuts.html
2025-04-12 10:22:55,047 - article_extractor - INFO - Extracting content from: https://www.nytimes.com/2025/04/11/nyregion/doge-treasury-lawsuit.html
2025-04-12 10:22:55,051 - article_extractor - INFO - Updated article https://www.nytimes.com/2025/04/11/business/economy/treasury-bonds-tariffs.html in database
2025-04-12 10:22:55,052 - article_extractor - INFO - Processed article 37/50: https://www.nytimes.com/2025/04/11/business/economy/treasury-bonds-tariffs.html
2025-04-12 10:22:55,056 - article_extractor - INFO - Updated article https://www.nytimes.com/2025/04/12/world/asia/taiwan-exporters-tariffs.html in database
2025-04-12 10:22:55,058 - article_extractor - INFO - Processed article 38/50: https://www.nytimes.com/2025/04/12/world/asia/taiwan-exporters-tariffs.html
2025-04-12 10:22:55,061 - article_extractor - INFO - Updated article https://www.nytimes.com/2025/04/11/us/politics/us-maryland-man-deportation-delay.html in database
2025-04-12 10:22:55,063 - article_extractor - INFO - Processed article 39/50: https://www.nytimes.com/2025/04/11/us/politics/us-maryland-man-deportation-delay.html
2025-04-12 10:22:55,066 - article_extractor - INFO - Updated article https://www.nytimes.com/2025/04/11/nyregion/khalil-jena-deportation-ruling.html in database
2025-04-12 10:22:55,067 - article_extractor - INFO - Processed article 40/50: https://www.nytimes.com/2025/04/11/nyregion/khalil-jena-deportation-ruling.html
2025-04-12 10:22:55,071 - article_extractor - INFO - Updated article https://www.nytimes.com/2025/04/11/us/politics/immigration-enforcement-places-of-worship.html in database
2025-04-12 10:22:55,072 - article_extractor - INFO - Processed article 41/50: https://www.nytimes.com/2025/04/11/us/politics/immigration-enforcement-places-of-worship.html
2025-04-12 10:22:57,890 - article_extractor - INFO - Extracting content from: https://www.nytimes.com/2025/04/12/world/middleeast/iran-nuclear-talks-whats-at-stake.html
2025-04-12 10:22:58,489 - article_extractor - INFO - Extracting content from: https://www.nytimes.com/2025/04/11/arts/television/doctor-who-disney-ncuti-gatwa.html

In [6]:
DB_FILE = os.path.join("../scrappers/articles.db")
conn = sqlite3.connect(DB_FILE)
cursor = conn.cursor()

df = pd.read_sql_query("SELECT * FROM articles WHERE status='COMPLETE'" , con=conn)

#extract complete content and looks for country names in each news article

creat a new column with all country names present in the content.

In [24]:
completed_df = df[df['status']=='COMPLETE']
country_names = [country.name for country in pycountry.countries]
query = '|'.join(country_names)

df['query_match'] = completed_df['content'].str.lower().str.contains(query)
df['query_match'] = completed_df['content'].str.contains(query, case=False)

/tmp/ipykernel_350983/2085291202.py:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df['query_match'] = completed_df['content'].str.lower().str.contains(query)
/tmp/ipykernel_350983/2085291202.py:6: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df['query_match'] = completed_df['content'].str.contains(query, case=False)

In [40]:
completed_df

,id,source_id,title,url,published_date,content,created_at,html_content,extraction_date,status,query_match
0,77,2,Treasury minister Darren Jones says globalisat...,https://www.bbc.com/news/articles/ckg10yjp7meo,2025-04-06T11:59:20,Chief Secretary to the Treasury Darren Jones h...,2025-04-06 12:00:11,"<html><body><div><div class=""sc-18fde0d6-0 dlW...",2025-04-06 14:00:15,COMPLETE,False
1,78,2,Man killed in shooting at Stanley house,https://www.bbc.com/news/articles/cwy7en200gyo,2025-04-06T10:14:47,Man in 50s killed in shooting at house\n\nSimo...,2025-04-06 12:00:11,"<html><body><div><article><p class=""sc-18fde0d...",2025-04-06 14:00:17,COMPLETE,False
2,80,2,Japanese Grand Prix: Max Verstappen steals Suz...,https://www.bbc.com/sport/formula1/articles/c4...,2025-04-06T11:19:02,McLaren's one chink of light in the race was t...,2025-04-06 12:00:11,"<html><body><div><div class=""ssrcss-7uxr49-Ric...",2025-04-06 14:00:17,COMPLETE,False
3,81,2,Father and daughter who died in Ingoldmells ca...,https://www.bbc.com/news/articles/cqx4932x9vwo,2025-04-06T13:07:56,Two people who died following a fire at a cara...,2025-04-06 13:25:33,"<html><body><div><div class=""sc-18fde0d6-0 dlW...",2025-04-06 15:25:38,COMPLETE,False
4,82,2,UK Weather: Will the sunshine last until Easte...,https://www.bbc.com/weather/articles/c62ge0mv876o,2025-04-06T12:38:09,A shift in the centre of the high pressure sou...,2025-04-06 13:25:33,"<html><body><div><div class=""ssrcss-7uxr49-Ric...",2025-04-06 15:25:43,COMPLETE,False
...,...,...,...,...,...,...,...,...,...,...,...
104,197,3,Judge Says One DOGE Member Can Access Sensitiv...,https://www.nytimes.com/2025/04/11/nyregion/do...,2025-04-12T01:17:08,A Manhattan federal judge ruled on Friday that...,2025-04-12 08:03:30,"<html><body><div><div class=""css-s99gbd StoryB...",2025-04-12 10:22:57,COMPLETE,False
105,198,3,What to Know About U.S. Talks With Iran Over I...,https://www.nytimes.com/2025/04/12/world/middl...,2025-04-12T04:01:16,A brief handshake may be the most likely outco...,2025-04-12 08:03:30,"<html><body><div><div class=""css-s99gbd StoryB...",2025-04-12 10:23:01,COMPLETE,False
106,199,3,Has Disney+ Changed ‘Doctor Who’? U.S. and U.K...,https://www.nytimes.com/2025/04/11/arts/televi...,2025-04-11T04:01:09,"Last year, when Disney+ was spending big to pr...",2025-04-12 08:03:30,"<html><body><div><div class=""css-s99gbd StoryB...",2025-04-12 10:23:01,COMPLETE,False
107,200,3,Hudson River Helicopter Crash Is a Tragic End ...,https://www.nytimes.com/2025/04/11/nyregion/se...,2025-04-11T21:13:28,“Living the dream.”\n\nThat was how Seankese J...,2025-04-12 08:03:30,"<html><body><div><div class=""css-s99gbd StoryB...",2025-04-12 10:23:01,COMPLETE,False
108,201,3,Boeing Helped Power Russia’s Economy. Could It...,https://www.nytimes.com/2025/04/12/world/europ...,2025-04-12T07:26:56,"To hear President Vladimir V. Putin tell it, R...",2025-04-12 08:03:30,"<html><body><div><div class=""css-s99gbd StoryB...",2025-04-12 10:23:01,COMPLETE,False

In [28]:
query

"Aruba|Afghanistan|Angola|Anguilla|Åland Islands|Albania|Andorra|United Arab Emirates|Argentina|Armenia|American Samoa|Antarctica|French Southern Territories|Antigua and Barbuda|Australia|Austria|Azerbaijan|Burundi|Belgium|Benin|Bonaire, Sint Eustatius and Saba|Burkina Faso|Bangladesh|Bulgaria|Bahrain|Bahamas|Bosnia and Herzegovina|Saint Barthélemy|Belarus|Belize|Bermuda|Bolivia, Plurinational State of|Brazil|Barbados|Brunei Darussalam|Bhutan|Bouvet Island|Botswana|Central African Republic|Canada|Cocos (Keeling) Islands|Switzerland|Chile|China|Côte d'Ivoire|Cameroon|Congo, The Democratic Republic of the|Congo|Cook Islands|Colombia|Comoros|Cabo Verde|Costa Rica|Cuba|Curaçao|Christmas Island|Cayman Islands|Cyprus|Czechia|Germany|Djibouti|Dominica|Denmark|Dominican Republic|Algeria|Ecuador|Egypt|Eritrea|Western Sahara|Spain|Estonia|Ethiopia|Finland|Fiji|Falkland Islands (Malvinas)|France|Faroe Islands|Micronesia, Federated States of|Gabon|United Kingdom|Georgia|Guernsey|Ghana|Gibraltar|Guinea|Guadeloupe|Gambia|Guinea-Bissau|Equatorial Guinea|Greece|Grenada|Greenland|Guatemala|French Guiana|Guam|Guyana|Hong Kong|Heard Island and McDonald Islands|Honduras|Croatia|Haiti|Hungary|Indonesia|Isle of Man|India|British Indian Ocean Territory|Ireland|Iran, Islamic Republic of|Iraq|Iceland|Israel|Italy|Jamaica|Jersey|Jordan|Japan|Kazakhstan|Kenya|Kyrgyzstan|Cambodia|Kiribati|Saint Kitts and Nevis|Korea, Republic of|Kuwait|Lao People's Democratic Republic|Lebanon|Liberia|Libya|Saint Lucia|Liechtenstein|Sri Lanka|Lesotho|Lithuania|Luxembourg|Latvia|Macao|Saint Martin (French part)|Morocco|Monaco|Moldova, Republic of|Madagascar|Maldives|Mexico|Marshall Islands|North Macedonia|Mali|Malta|Myanmar|Montenegro|Mongolia|Northern Mariana Islands|Mozambique|Mauritania|Montserrat|Martinique|Mauritius|Malawi|Malaysia|Mayotte|Namibia|New Caledonia|Niger|Norfolk Island|Nigeria|Nicaragua|Niue|Netherlands|Norway|Nepal|Nauru|New Zealand|Oman|Pakistan|Panama|Pitcairn|Peru|Philippines|Palau|Papua New Guinea|Poland|Puerto Rico|Korea, Democratic People's Republic of|Portugal|Paraguay|Palestine, State of|French Polynesia|Qatar|Réunion|Romania|Russian Federation|Rwanda|Saudi Arabia|Sudan|Senegal|Singapore|South Georgia and the South Sandwich Islands|Saint Helena, Ascension and Tristan da Cunha|Svalbard and Jan Mayen|Solomon Islands|Sierra Leone|El Salvador|San Marino|Somalia|Saint Pierre and Miquelon|Serbia|South Sudan|Sao Tome and Principe|Suriname|Slovakia|Slovenia|Sweden|Eswatini|Sint Maarten (Dutch part)|Seychelles|Syrian Arab Republic|Turks and Caicos Islands|Chad|Togo|Thailand|Tajikistan|Tokelau|Turkmenistan|Timor-Leste|Tonga|Trinidad and Tobago|Tunisia|Türkiye|Tuvalu|Taiwan, Province of China|Tanzania, United Republic of|Uganda|Ukraine|United States Minor Outlying Islands|Uruguay|United States|Uzbekistan|Holy See (Vatican City State)|Saint Vincent and the Grenadines|Venezuela, Bolivarian Republic of|Virgin Islands, British|Virgin Islands, U.S.|Viet Nam|Vanuatu|Wallis and Futuna|Samoa|Yemen|South Africa|Zambia|Zimbabwe"

In [32]:
len(df['content'][34])

874

In [18]:
def filter_content():
    for index, row in df.iterrows():
        if row['status']=="COMPLETED":

,id,source_id,title,url,published_date,content,created_at,html_content,extraction_date,status
0,1,1,Dominion still has pending lawsuits against el...,https://www.cnn.com/business/live-news/fox-new...,None,None,2025-04-06 09:15:11,None,None,FAILED
1,2,1,Russia is 'going backwards' in equipment and d...,https://www.cnn.com/europe/live-news/russia-uk...,None,None,2025-04-06 09:15:11,None,None,FAILED
2,3,1,Podcast: One country musician is calling for o...,https://www.cnn.com/audio/podcasts/the-assignm...,None,None,2025-04-06 09:15:11,None,None,FAILED
3,4,1,Bidets save you money and reduce waste — we te...,https://www.cnn.com/cnn-underscored/reviews/be...,None,None,2025-04-06 09:15:11,None,None,FAILED
4,5,1,50+ products to make your life easier and our ...,https://www.cnn.com/cnn-underscored/home/edito...,None,None,2025-04-06 09:15:11,None,None,FAILED
...,...,...,...,...,...,...,...,...,...,...
97,98,3,The Future of Baseball - The New York Times,https://www.nytimes.com/2025/04/06/briefing/ba...,2025-04-06T11:16:53,"A new baseball season is underway, and the spo...",2025-04-06 13:25:36,"<html><body><div><div class=""css-s99gbd StoryB...",2025-04-06 15:25:52,COMPLETE
98,99,3,Recovering Pope Francis Surprises Pilgrims Wit...,https://www.nytimes.com/2025/04/06/world/europ...,2025-04-06T12:32:47,"As entrances go, this one was both unexpected ...",2025-04-06 13:25:36,"<html><body><div><div class=""css-s99gbd StoryB...",2025-04-06 15:25:52,COMPLETE
99,100,3,Long-Running Storm Drenches Central U.S. but S...,https://www.nytimes.com/2025/04/06/weather/sto...,2025-04-06T12:27:55,The huge storm system that has caused widespre...,2025-04-06 13:25:36,"<html><body><div><div class=""css-s99gbd StoryB...",2025-04-06 15:25:52,COMPLETE
100,101,3,This Agency Fights Corruption. New York City L...,https://www.nytimes.com/2025/04/06/nyregion/ny...,2025-04-06T07:00:06,"In recent months, New York City’s government h...",2025-04-06 13:25:36,"<html><body><div><div class=""css-s99gbd StoryB...",2025-04-06 15:25:52,COMPLETE
101,102,3,Russia Strikes Kyiv as Ukraine Mourns Deadly A...,https://www.nytimes.com/2025/04/06/world/europ...,2025-04-06T11:49:55,Russia bombarded Ukraine with ballistic missil...,2025-04-06 13:25:36,"<html><body><div><div class=""css-s99gbd StoryB...",2025-04-06 15:25:52,COMPLETE

In [13]:
import transformers
from transformers import pipeline
import accelerate
print(f"Transformers version: {accelerate.__version__}")

# Try reinstalling transformers with specific version
#!pip install transformers==4.30.2 --force-reinstall

Transformers version: 1.6.0

In [15]:
import torch

In [18]:
!uv add ollama

Resolved 88 packages in 573ms
⠙ Preparing packages... (0/10)                                                  ⠋ Preparing packages... (0/0)
⠙ Preparing packages... (0/10)---     0 B/56.89 KiB
annotated-types ------------------------------     0 B/13.32 KiB
⠙ Preparing packages... (0/10)---     0 B/56.89 KiB
annotated-types ------------------------------     0 B/13.32 KiB
⠙ Preparing packages... (0/10)--- 14.84 KiB/56.89 KiB
annotated-types ------------------------------ 13.32 KiB/13.32 KiB
⠙ Preparing packages... (0/10)--- 14.84 KiB/56.89 KiB
⠙ Preparing packages... (0/10)--- 14.84 KiB/56.89 KiB
h11        ------------------------------ 14.84 KiB/56.89 KiB
⠙ Preparing packages... (0/10)---     0 B/432.91 KiB
h11        ------------------------------ 14.84 KiB/56.89 KiB
anyio      ------------------------------     0 B/98.55 KiB
⠙ Preparing packages... (0/10)---     0 B/432.91 KiB
h11        ------------------------------ 14.84 KiB/56.89 KiB
httpcore   ------------------------------     0 B/76.71 KiB
anyio      ------------------------------     0 B/98.55 KiB
⠙ Preparing packages... (0/10)---     0 B/432.91 KiB
h11        ------------------------------ 14.84 KiB/56.89 KiB
httpx      ------------------------------     0 B/71.79 KiB
httpcore   ------------------------------     0 B/76.71 KiB
anyio      ------------------------------     0 B/98.55 KiB
⠙ Preparing packages... (0/10)---     0 B/432.91 KiB
typing-inspection ------------------------------     0 B/13.79 KiB
h11        ------------------------------ 14.84 KiB/56.89 KiB
httpx      ------------------------------     0 B/71.79 KiB
httpcore   ------------------------------     0 B/76.71 KiB
anyio      ------------------------------     0 B/98.55 KiB
⠙ Preparing packages... (0/10)---     0 B/432.91 KiB
typing-inspection ------------------------------     0 B/13.79 KiB
h11        ------------------------------ 14.84 KiB/56.89 KiB
httpx      ------------------------------     0 B/71.79 KiB
httpcore   ------------------------------     0 B/76.71 KiB
anyio      ------------------------------     0 B/98.55 KiB
⠙ Preparing packages... (0/10)--- 14.89 KiB/432.91 KiB
typing-inspection ------------------------------     0 B/13.79 KiB
h11        ------------------------------ 14.84 KiB/56.89 KiB
httpx      ------------------------------     0 B/71.79 KiB
httpcore   ------------------------------     0 B/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
⠙ Preparing packages... (0/10)--- 14.89 KiB/432.91 KiB
typing-inspection ------------------------------     0 B/13.79 KiB
h11        ------------------------------ 14.84 KiB/56.89 KiB
httpx      ------------------------------     0 B/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
⠙ Preparing packages... (0/10)--- 14.89 KiB/432.91 KiB
typing-inspection ------------------------------     0 B/13.79 KiB
h11        ------------------------------ 14.84 KiB/56.89 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
⠙ Preparing packages... (0/10)--- 14.89 KiB/432.91 KiB
typing-inspection ------------------------------ 13.79 KiB/13.79 KiB
h11        ------------------------------ 14.84 KiB/56.89 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
⠙ Preparing packages... (0/10)--- 14.89 KiB/432.91 KiB
typing-inspection ------------------------------ 13.79 KiB/13.79 KiB
h11        ------------------------------ 30.84 KiB/56.89 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
⠙ Preparing packages... (0/10)--- 14.89 KiB/432.91 KiB
ollama     ------------------------------     0 B/12.90 KiB
typing-inspection ------------------------------ 13.79 KiB/13.79 KiB
h11        ------------------------------ 30.84 KiB/56.89 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
⠙ Preparing packages... (0/10)--- 14.89 KiB/432.91 KiB
ollama     ------------------------------ 12.90 KiB/12.90 KiB
typing-inspection ------------------------------ 13.79 KiB/13.79 KiB
h11        ------------------------------ 30.84 KiB/56.89 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
⠙ Preparing packages... (0/10)--- 14.89 KiB/432.91 KiB
sniffio    ------------------------------     0 B/10.00 KiB
ollama     ------------------------------ 12.90 KiB/12.90 KiB
typing-inspection ------------------------------ 13.79 KiB/13.79 KiB
h11        ------------------------------ 30.84 KiB/56.89 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
⠙ Preparing packages... (0/10)--- 14.89 KiB/432.91 KiB
sniffio    ------------------------------     0 B/10.00 KiB
ollama     ------------------------------ 12.90 KiB/12.90 KiB
typing-inspection ------------------------------ 13.79 KiB/13.79 KiB
h11        ------------------------------ 30.84 KiB/56.89 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
pydantic   ------------------------------ 14.89 KiB/432.91 KiB
⠙ Preparing packages... (0/10)------     0 B/1.92 MiB
sniffio    ------------------------------     0 B/10.00 KiB
typing-inspection ------------------------------ 13.79 KiB/13.79 KiB
h11        ------------------------------ 30.84 KiB/56.89 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
pydantic   ------------------------------ 14.89 KiB/432.91 KiB
⠙ Preparing packages... (0/10)------     0 B/1.92 MiB
sniffio    ------------------------------     0 B/10.00 KiB
h11        ------------------------------ 30.84 KiB/56.89 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
pydantic   ------------------------------ 14.89 KiB/432.91 KiB
⠙ Preparing packages... (0/10)------     0 B/1.92 MiB
sniffio    ------------------------------     0 B/10.00 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
pydantic   ------------------------------ 14.89 KiB/432.91 KiB
⠹ Preparing packages... (4/10)------     0 B/1.92 MiB
sniffio    ------------------------------     0 B/10.00 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
pydantic   ------------------------------ 14.89 KiB/432.91 KiB
⠸ Preparing packages... (4/10)------     0 B/1.92 MiB
sniffio    ------------------------------     0 B/10.00 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
pydantic   ------------------------------ 14.89 KiB/432.91 KiB
⠸ Preparing packages... (4/10)------     0 B/1.92 MiB
sniffio    ------------------------------ 10.00 KiB/10.00 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
pydantic   ------------------------------ 14.89 KiB/432.91 KiB
⠸ Preparing packages... (4/10)------     0 B/1.92 MiB
sniffio    ------------------------------ 10.00 KiB/10.00 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
pydantic   ------------------------------ 14.89 KiB/432.91 KiB
⠸ Preparing packages... (4/10)------ 14.91 KiB/1.92 MiB
sniffio    ------------------------------ 10.00 KiB/10.00 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 14.88 KiB/98.55 KiB
pydantic   ------------------------------ 30.89 KiB/432.91 KiB
⠸ Preparing packages... (4/10)------ 14.91 KiB/1.92 MiB
sniffio    ------------------------------ 10.00 KiB/10.00 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 14.88 KiB/76.71 KiB
anyio      ------------------------------ 30.88 KiB/98.55 KiB
pydantic   ------------------------------ 30.89 KiB/432.91 KiB
⠸ Preparing packages... (4/10)------ 14.91 KiB/1.92 MiB
sniffio    ------------------------------ 10.00 KiB/10.00 KiB
httpx      ------------------------------ 14.89 KiB/71.79 KiB
httpcore   ------------------------------ 30.88 KiB/76.71 KiB
anyio      ------------------------------ 30.88 KiB/98.55 KiB
pydantic   ------------------------------ 30.89 KiB/432.91 KiB
⠸ Preparing packages... (4/10)------ 14.91 KiB/1.92 MiB
sniffio    ------------------------------ 10.00 KiB/10.00 KiB
httpx      ------------------------------ 30.89 KiB/71.79 KiB
httpcore   ------------------------------ 30.88 KiB/76.71 KiB
anyio      ------------------------------ 30.88 KiB/98.55 KiB
pydantic   ------------------------------ 30.89 KiB/432.91 KiB
⠸ Preparing packages... (4/10)------ 14.91 KiB/1.92 MiB
httpx      ------------------------------ 46.89 KiB/71.79 KiB
httpcore   ------------------------------ 46.88 KiB/76.71 KiB
anyio      ------------------------------ 55.72 KiB/98.55 KiB
pydantic   ------------------------------ 62.89 KiB/432.91 KiB
⠸ Preparing packages... (4/10)------ 30.91 KiB/1.92 MiB
httpx      ------------------------------ 62.89 KiB/71.79 KiB
httpcore   ------------------------------ 62.88 KiB/76.71 KiB
anyio      ------------------------------ 57.16 KiB/98.55 KiB
pydantic   ------------------------------ 77.33 KiB/432.91 KiB
⠸ Preparing packages... (4/10)------ 46.91 KiB/1.92 MiB
httpx      ------------------------------ 62.89 KiB/71.79 KiB
anyio      ------------------------------ 57.16 KiB/98.55 KiB
pydantic   ------------------------------ 77.33 KiB/432.91 KiB
⠸ Preparing packages... (4/10)------ 46.91 KiB/1.92 MiB
anyio      ------------------------------ 73.16 KiB/98.55 KiB
pydantic   ------------------------------ 93.33 KiB/432.91 KiB
⠸ Preparing packages... (4/10)------ 46.91 KiB/1.92 MiB
pydantic   ------------------------------ 141.33 KiB/432.91 KiB
⠸ Preparing packages... (4/10)------ 110.91 KiB/1.92 MiB
pydantic   ------------------------------ 253.33 KiB/432.91 KiB
⠼ Preparing packages... (8/10)------ 222.91 KiB/1.92 MiB
⠼ Preparing packages... (8/10)------ 456.56 KiB/1.92 MiB
⠼ Preparing packages... (8/10)------ 680.56 KiB/1.92 MiB
⠼ Preparing packages... (8/10)------ 1.22 MiB/1.92 MiB
Prepared 10 packages in 761ms
Installed 10 packages in 23ms
 + annotated-types==0.7.0
 + anyio==4.9.0
 + h11==0.14.0
 + httpcore==1.0.7
 + httpx==0.28.1
 + ollama==0.4.7
 + pydantic==2.11.2
 + pydantic-core==2.33.1
 + sniffio==1.3.1
 + typing-inspection==0.4.0

In [16]:
print(torch.cuda.is_available())

True

In [17]:
from transformers import pipeline
classifier = pipeline("zero-shot-classification",
                      model="facebook/bart-large-mnli")

NameError: name 'init_empty_weights' is not defined